# Generated by Django 3.2.9 on 2021-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0002_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limchecklist',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='limparameters',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='limproductioncounters',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='productionsheetlim',
            name='approver',
        ),
    ]
