# Generated by Django 3.2.9 on 2021-11-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('LO', 'LIM-OPERATOR'), ('PO', 'PRINT-OPERATOR'), ('PM', 'PROCESS-MANAGER'), ('SI', 'SHIFT-INCHARGE')], default=None, max_length=30),
        ),
    ]
